Repository OMZigak/KKUM_ANDROID, pull requests merged in 2024-08, with the labels that each got.

#116 [Hotfix/#113] reissue mutex활용
  .editorconfig
  core/domain/.gitignore
  core/domain/build.gradle.kts
  core/network/src/main/java/com/teamkkumul/core/network/api/LoginService.kt
  core/network/src/main/java/com/teamkkumul/core/network/di/RetrofitModule.kt
  core/network/src/main/java/com/teamkkumul/core/network/interceptor/TokenInterceptor.kt
  feature/build.gradle.kts
  feature/src/main/res/layout/fragment_home.xml
  settings.gradle.kts
Labels: 😮 [HOTFIX], 🐶 찬우

#114 [Feat/#111] group list error handling
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MyGroupRepositoryImpl.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/MyGroupViewModel.kt
Labels: 🔧 [FIX], 👽 효은

#117 [Fix/#115] group detail error handling
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MyGroupRepositoryImpl.kt
  core/model/src/main/java/com/teamkkumul/model/MeetUpDetailFriendModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/MyGroupFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/MyGroupViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
  feature/src/main/res/layout/fragment_meet_up_container.xml
  feature/src/main/res/layout/fragment_my_group.xml
  feature/src/main/res/layout/fragment_my_group_detail.xml
Labels: 🔧 [FIX], 👽 효은

#121 [FIX/#119] 약속 마치기 기능 수정
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetUpRepositoryImpl.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
  feature/src/main/res/layout/fragment_late_person.xml
  feature/src/main/res/layout/view_late_person_empty.xml
Labels: 🔧 [FIX], 🐻‍❄️ 윤서

#120 [Fix/#118] meet up create error handling
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetUpCreateLocationRepositoryImpl.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/KeyStorage.kt
  feature/src/main/res/drawable/pg_meet_up_green.xml
  feature/src/main/res/layout/fragment_meet_up_create.xml
  feature/src/main/res/layout/fragment_meet_up_create_complete.xml
  feature/src/main/res/layout/fragment_meet_up_friend_plus.xml
  feature/src/main/res/layout/fragment_meet_up_level.xml
  feature/src/main/res/layout/view_toolbar.xml
  feature/src/main/res/values/themes.xml
Labels: 🔧 [FIX], 👽 효은

#125 [Fix/#110] ready status message
  core/data/build.gradle.kts
  core/data/src/main/java/com/teamkkumul/core/data/mapper/MyGroupMapper.kt
  core/data/src/main/java/com/teamkkumul/core/data/utils/ContentUriRequestBody.kt
  core/model/src/main/java/com/teamkkumul/model/MyGroupDetailMemeberSealedItem.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/view/DiffCallbackExt.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewVisibleExt.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/complete/ReadyInputCompletedFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt
  feature/src/main/res/layout/fragment_ready_status.xml
  feature/src/main/res/navigation/nav_graph.xml
  gradle/libs.versions.toml
Labels: 🔧 [FIX], 🐶 찬우

#123 [FIX/#122] 모임 생성, 가입 에러 핸들링
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetingsRepositoryImpl.kt
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/AddNewGroupFragment.kt
  feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/KeyStorage.kt
  feature/src/main/res/layout/fragment_late_person.xml
Labels: 🔧 [FIX], 🐻‍❄️ 윤서

#131 [Fix/#127] meet up create error
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt
  feature/src/main/res/layout/fragment_meet_up_create.xml
  feature/src/main/res/layout/fragment_meet_up_detail.xml
  feature/src/main/res/layout/fragment_my_group_detail.xml
  feature/src/main/res/layout/item_my_group_remain_meet_up.xml
Labels: 🔧 [FIX], 👽 효은

#130 [Feat/#129] sprint my group detail
  core/ui/src/main/java/com/teamkkumul/core/ui/base/BindingBottomSheetFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/KeyStorage.kt
  feature/src/main/res/drawable/ic_bottom_sheet_divide.xml
  feature/src/main/res/drawable/ic_btn_more_36.xml
  feature/src/main/res/drawable/shape_rect_white_fill_8.xml
  feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
  feature/src/main/res/layout/fragment_meet_up_create.xml
  feature/src/main/res/layout/fragment_meet_up_friend_plus.xml
  feature/src/main/res/layout/fragment_my_group.xml
  feature/src/main/res/layout/fragment_my_group_detail.xml
  feature/src/main/res/layout/view_toolbar.xml
  feature/src/main/res/navigation/nav_graph.xml
  feature/src/main/res/values/strings.xml
  feature/src/main/res/values/themes.xml
Labels: ⭐ [FEAT], 👽 효은, 🌻 XML

#136 [FEAT/#133] 모임, 약속 나가기, 약속 삭제 dialog 구현
  feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/DeleteDialogType.kt
  feature/src/main/java/com/teamkkumul/feature/utils/KeyStorage.kt
  feature/src/main/java/com/teamkkumul/feature/utils/bottomsheet/BottomSheetMeetUpExitFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/bottomsheet/MyGroupExitBottomSheetFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt
  feature/src/main/res/drawable/ic_dialog_delete_meet_up.xml
  feature/src/main/res/drawable/ic_dialog_leave_meet_up.xml
  feature/src/main/res/drawable/ic_dialog_leave_my_group.xml
  feature/src/main/res/drawable/ic_meet_up_detail_receipt.xml
  feature/src/main/res/layout/fragment_dialog_delete.xml
  feature/src/main/res/layout/fragment_exit_meet_up_bottom_sheet.xml
  feature/src/main/res/layout/fragment_meet_up_detail.xml
  feature/src/main/res/navigation/nav_graph.xml
  feature/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💚 [UI], 🐻‍❄️ 윤서, 🌻 XML

#143 [Fix/#142] d day color
  core/ui/src/main/java/com/teamkkumul/core/ui/util/view/recyclerviewExt.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/home/viewholder/HomeMeetUpViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/viewholder/MyGroupDetailMeetUpViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/setDday.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/timeUtil.kt
Labels: 🔧 [FIX], 🐶 찬우

#147 [UI/#145] our ready status UI
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusAdapter.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/viewholder/ReadyStatusFriendItemDecoration.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/viewholder/ReadyStatusViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
  feature/src/main/res/drawable/shape_rect_top_20.xml
  feature/src/main/res/layout/fragment_dialog_delete.xml
  feature/src/main/res/layout/fragment_ready_status.xml
  feature/src/main/res/layout/item_ready_status.xml
  gradle.properties
Labels: 💚 [UI], 🐶 찬우

#148 [FEAT/#141] 약속 나가기, 삭제하기 서버 통신
  core/data/src/main/java/com/teamkkumul/core/data/repository/MeetUpRepository.kt
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetUpRepositoryImpl.kt
  core/network/src/main/java/com/teamkkumul/core/network/api/MeetUpService.kt
  core/network/src/main/java/com/teamkkumul/core/network/dto/request/RequestMeetUpCreateDto.kt
  core/network/src/main/java/com/teamkkumul/core/network/dto/response/ResponseMeetUpDetailDto.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewTextColorExt.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/bottomsheet/BottomSheetMeetUpExitFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/timeUtil.kt
  feature/src/main/res/drawable/ic_meet_up_detail_receipt_gray.xml
  feature/src/main/res/layout/fragment_meet_up_detail.xml
  feature/src/main/res/navigation/nav_graph.xml
  feature/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐻‍❄️ 윤서, 서버통신

#149 [Feat/#144] logout, 회원탈퇴
  core/data/src/main/java/com/teamkkumul/core/data/di/DataModule.kt
  core/data/src/main/java/com/teamkkumul/core/data/repository/AuthRepository.kt
  core/data/src/main/java/com/teamkkumul/core/data/repository/UserInfoRepository.kt
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/AuthRepositoryImpl.kt
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/UserInfoRepositoryImpl.kt
  core/datastore/src/main/java/com/teamkkumul/core/datastore/datasource/DefaultKumulPreferenceDatasource.kt
  core/datastore/src/main/java/com/teamkkumul/core/datastore/datasource/KumulPreferencesDataSource.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/teamkkumul/core/network/api/LogoutService.kt
  core/network/src/main/java/com/teamkkumul/core/network/di/ApiModule.kt
  core/network/src/main/java/com/teamkkumul/core/network/interceptor/TokenInterceptor.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/view/RecyclerviewExt.kt
  feature/src/main/java/com/teamkkumul/feature/MainActivity.kt
  feature/src/main/java/com/teamkkumul/feature/auth/LoginViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/home/viewholder/HomeMeetUpViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/viewholder/MyGroupDetailMeetUpViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/splash/SplashViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/utils/bottomsheet/BottomSheetMeetUpExitFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/bottomsheet/MyGroupExitBottomSheetFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/utils/extension/DeleteDialogExt.kt
  feature/src/main/java/com/teamkkumul/feature/utils/extension/LevelExt.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/GetCurrentTime.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/SetDday.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt
  feature/src/main/java/com/teamkkumul/feature/utils/type/DeleteDialogType.kt
  feature/src/main/java/com/teamkkumul/feature/utils/type/LevelColorType.kt
  feature/src/main/res/drawable/ic_my_page_profile.xml
  feature/src/main/res/layout/fragment_dialog_delete.xml
  feature/src/main/res/layout/fragment_home.xml
  feature/src/main/res/layout/fragment_my_page.xml
  feature/src/main/res/navigation/nav_graph.xml
  feature/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐶 찬우

#150 [FEAT/#124] 마이페이지 프로필 사진 수정 구현
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/ProfileRepositoryImpl.kt
  feature/src/main/java/com/teamkkumul/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/AddNewGroupFragment.kt
  feature/src/main/java/com/teamkkumul/feature/signup/SetNameActivity.kt
  feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
  feature/src/main/java/com/teamkkumul/feature/utils/KeyStorage.kt
Labels: ⭐ [FEAT], 🔧 [FIX], 🐻‍❄️ 윤서, 서버통신

#156 [REFACTOR/#154] 1차 스프린트 구현 수정, 리팩토링
  core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewTextColorExt.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/SetDday.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt
  feature/src/main/res/layout/fragment_meet_up_detail.xml
  feature/src/main/res/navigation/nav_graph.xml
Labels: 🔧 [FIX], ♻️ [REFACTOR], 🐻‍❄️ 윤서

#158 [Refactor/#155] 약속 수정하기 로직 수정
  core/data/src/main/java/com/teamkkumul/core/data/mapper/MeetUpMapper.kt
  core/model/src/main/java/com/teamkkumul/model/MeetUpCreateModel.kt
  core/model/src/main/java/com/teamkkumul/model/MeetUpDetailModel.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewVisibleExt.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFriendViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateLocationViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpLevelViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpSharedViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt
  feature/src/main/res/drawable/shape_white0_radius_8.xml
  feature/src/main/res/layout/fragment_meet_up_create.xml
  feature/src/main/res/layout/fragment_meet_up_create_complete.xml
  feature/src/main/res/layout/fragment_meet_up_create_location.xml
  feature/src/main/res/layout/fragment_meet_up_friend_plus.xml
  feature/src/main/res/layout/fragment_meet_up_level.xml
  feature/src/main/res/layout/fragment_my_group_detail.xml
  feature/src/main/res/values/themes.xml
Labels: ♻️ [REFACTOR], 👽 효은

#159 [REFACTOR/#154] 프로필 사진 갤러리 퍼미션 분기처리, chip group 선택됨 구현
  app/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
  feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
  feature/src/main/res/navigation/nav_graph.xml
Labels: 🔧 [FIX], ♻️ [REFACTOR], 🐻‍❄️ 윤서

#163 [REFACTOR/#160] 1차 스프린트 디자인 수정, drawable 파일 정리
  core/data/src/main/java/com/teamkkumul/core/data/mapper/MeetUpMapper.kt
  core/data/src/main/java/com/teamkkumul/core/data/repository/MeetUpRepository.kt
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetUpRepositoryImpl.kt
  core/model/src/main/java/com/teamkkumul/model/MeetUpParticipantItem.kt
  core/model/src/main/java/com/teamkkumul/model/MeetUpSealedItem.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFriendViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailListAdapter.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/viewholder/MeetUpDetailFriendPlusViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/viewholder/MeetUpDetailFriendViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/utils/type/DeleteDialogType.kt
  feature/src/main/res/drawable/ic_dialog_leave_meet_up.xml
  feature/src/main/res/drawable/ic_enter_invitation_code_check_green_24.xml
  feature/src/main/res/drawable/ic_penalty_icon.xml
  feature/src/main/res/drawable/ic_profile_empty.png
  feature/src/main/res/drawable/img_profile_basic.png
  feature/src/main/res/layout/fragment_dialog_delete.xml
  feature/src/main/res/layout/fragment_enter_invitation_code.xml
  feature/src/main/res/layout/fragment_late_person.xml
  feature/src/main/res/layout/fragment_my_group_detail.xml
  feature/src/main/res/layout/fragment_my_page.xml
  feature/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], 🐻‍❄️ 윤서

#157 [Fix/#126] home button help text + 불필요한 파일, 코드 삭제
  core/data/src/main/java/com/teamkkumul/core/data/di/DataModule.kt
  core/data/src/main/java/com/teamkkumul/core/data/mapper/ReqresMapper.kt
  core/data/src/main/java/com/teamkkumul/core/data/repository/ReqresRepository.kt
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/ReqresRepositoryImpl.kt
  core/designsystem/src/main/java/com/teamkkumul/core/designsystem/component/Row.kt
  core/model/src/main/java/com/teamkkumul/model/BaseApi.kt
  core/model/src/main/java/com/teamkkumul/model/example/ReqresModel.kt
  core/model/src/main/java/com/teamkkumul/model/example/User.kt
  core/network/src/main/java/com/teamkkumul/core/network/api/ReqresService.kt
  core/network/src/main/java/com/teamkkumul/core/network/di/ApiModule.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/util/fragment/FragmentExt.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/view/EditTextExt.kt
  feature/src/main/java/com/teamkkumul/feature/SearchViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/compose/ExampleComposeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/compose/ExampleComposeViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/compose/ExampleRoute.kt
  feature/src/main/java/com/teamkkumul/feature/compose/model/ExampleSideEffect.kt
  feature/src/main/java/com/teamkkumul/feature/compose/model/ExampleState.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/utils/extension/LevelExt.kt
  feature/src/main/java/com/teamkkumul/feature/utils/extension/observeBtnState.kt
  feature/src/main/java/com/teamkkumul/feature/utils/model/BtnState.kt
  feature/src/main/res/layout/fragment_example_compose.xml
  feature/src/main/res/layout/fragment_home.xml
  feature/src/main/res/layout/fragment_ready_status.xml
  feature/src/main/res/layout/item_friend.xml
  feature/src/main/res/navigation/nav_graph.xml
  feature/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐶 찬우
