Repository OMZigak/KKUM_ANDROID, pull requests merged in 2024-09, with the labels that each got.

#165 #126 [hotfix] : 마진 에러 수정
  app/src/main/AndroidManifest.xml
  feature/src/main/AndroidManifest.xml
  feature/src/main/res/layout/fragment_home.xml
Labels: 💚 [UI], 🐶 찬우

#170 [Fix/#169] 1차 스프린트 QA 수정사항
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt
  feature/src/main/res/layout/fragment_meet_up_create_complete.xml
  feature/src/main/res/layout/fragment_meet_up_level.xml
Labels: 🔧 [FIX], 👽 효은

#173 [Hotfix/#167] firebase error
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: 😮 [HOTFIX], 🐶 찬우

#174 [Hotfix/#172] home qa
  feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/home/viewholder/HomeMeetUpViewHolder.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/utils/extension/observeBtnState.kt
  feature/src/main/java/com/teamkkumul/feature/utils/model/BtnState.kt
  feature/src/main/java/com/teamkkumul/feature/utils/type/ReadyBtnTextType.kt
  feature/src/main/res/values/strings.xml
Labels: 😮 [HOTFIX], 🐶 찬우

#168 [FIX/#166] 1차 스프린트 QA 반영
  core/data/src/main/java/com/teamkkumul/core/data/repository/ProfileRepository.kt
  core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/ProfileRepositoryImpl.kt
  core/network/src/main/java/com/teamkkumul/core/network/api/ProfileService.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
  feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
  feature/src/main/java/com/teamkkumul/feature/signup/SetProfileViewModel.kt
  feature/src/main/res/layout/fragment_dialog_invitation_code.xml
  feature/src/main/res/layout/fragment_enter_invitation_code.xml
  feature/src/main/res/layout/fragment_meet_up_detail.xml
  feature/src/main/res/layout/fragment_meet_up_level.xml
  feature/src/main/res/values/strings.xml
Labels: 🔧 [FIX], 🐻‍❄️ 윤서, 서버통신

#175 [Hotfix/#171] ready status qa
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/model/TimeTextState.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt
Labels: 😮 [HOTFIX], 🐶 찬우

#180 [FIX/#177] 스프린트 2차 QA 반영
  feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
  feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
  feature/src/main/res/drawable/ic_leave_meet_up_receipt_gray.xml
  feature/src/main/res/layout/fragment_dialog_delete.xml
  feature/src/main/res/navigation/nav_graph.xml
  feature/src/main/res/values/strings.xml
Labels: 🔧 [FIX], 🐻‍❄️ 윤서

#185 [fix/#176] 스프린트 3차 QA
  feature/src/main/res/layout/fragment_my_group_detail.xml
Labels: 🔧 [FIX]

#190 [Refactor/#188] 4차 qa
  core/model/src/main/java/com/teamkkumul/model/home/HomeReadyStatusModel.kt
  core/ui/src/main/java/com/teamkkumul/core/ui/util/bundle/getSafeParcelable.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamkkumul/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputFragment.kt
  feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt
  feature/src/main/java/com/teamkkumul/feature/utils/KeyStorage.kt
  feature/src/main/java/com/teamkkumul/feature/utils/time/GetCurrentTime.kt
Labels: 🔧 [FIX], 🐶 찬우

#193 #189 [feat] : 내 모임의 약속 d-day 기준으로 정렬 usecase 구현
  core/domain/src/main/java/com/chanu/core/domain/usecase/GetMyGroupMeetUpUseCase.kt
  feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt
Labels: ⭐ [FEAT], 🐶 찬우

#200 #199 [chore] : "을" 제거
  feature/src/main/res/values/strings.xml
Labels: 🛠️ [CHORE]

#204 [Fix/#203] 비트맵 압축 개선
  app/build.gradle.kts
  core/data/src/main/java/com/teamkkumul/core/data/utils/ContentUriRequestBody.kt
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🔧 [FIX], 🐶 찬우
